export { COURT, GRID_COLS, GRID_ROWS } from "./court";
export {
  CELL_BOUNCE_KEYFRAMES,
  NICKNAME_SHIMMER_KEYFRAMES,
  PULSE_KEYFRAMES,
  CELL_ANIMATION_DURATION,
  CELL_STAGGER_DELAY,
  TRAJECTORY_ANIMATION_DURATION,
  TRAJECTORY_TOTAL_TIME,
  NUMBERS_FADE_DURATION,
  getTrajectoryStagger,
} from "./animations";
export { TRAIL_COLORS, getTrailColor } from "./trailColors";

