import type { ZoneDefinition, ZoneSystem } from "../types";
import { metersToGrid } from "./grid";

// Traffic Light System (3 zones) - Classic coaching model for HALF COURT
const TRAFFIC_LIGHT_ZONES: ZoneDefinition[] = [
  {
    id: "green",
    name: "Net Zone",
    emoji: "🟢",
    color: "#10B981",
    yMin: 7,
    yMax: 10,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 7, 10),
    description: "Offensive position at the net",
    tacticalAdvice: "Finish points here with volleys and smashes",
  },
  {
    id: "orange",
    name: "Transition Zone",
    emoji: "🟠",
    color: "#F59E0B",
    yMin: 3.5,
    yMax: 7,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 3.5, 7),
    description: "Mid-court transition area",
    tacticalAdvice: "Move forward when possible, don't stay here long",
    isPressureZone: true,
  },
  {
    id: "red",
    name: "Defense Zone",
    emoji: "🔴",
    color: "#EF4444",
    yMin: 0,
    yMax: 3.5,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 0, 3.5),
    description: "Back court defensive position",
    tacticalAdvice: "Use lobs to reset, look for opportunities to advance",
    isPressureZone: true,
  },
];

// 6-Zone Tactical System - Split by depth AND side (HALF COURT)
const SIX_ZONE_SYSTEM: ZoneDefinition[] = [
  // Net zones (7-10m from back wall)
  {
    id: "net-deuce",
    name: "Net Deuce",
    emoji: "🎯",
    color: "#10B981",
    yMin: 7,
    yMax: 10,
    xMin: 0,
    xMax: 5,
    ...metersToGrid(0, 5, 7, 10),
    description: "Net position on deuce side",
    tacticalAdvice: "Control the diagonal, intercept crosses",
  },
  {
    id: "net-ad",
    name: "Net Ad",
    emoji: "🎯",
    color: "#059669",
    yMin: 7,
    yMax: 10,
    xMin: 5,
    xMax: 10,
    ...metersToGrid(5, 10, 7, 10),
    description: "Net position on advantage side",
    tacticalAdvice: "Protect the line, attack the middle",
  },
  // Transition zones (3.5-7m from back wall)
  {
    id: "trans-deuce",
    name: "Transition Deuce",
    emoji: "⚡",
    color: "#F59E0B",
    yMin: 3.5,
    yMax: 7,
    xMin: 0,
    xMax: 5,
    ...metersToGrid(0, 5, 3.5, 7),
    description: "Mid-court deuce side",
    tacticalAdvice: "Move up or back quickly",
    isPressureZone: true,
  },
  {
    id: "trans-ad",
    name: "Transition Ad",
    emoji: "⚡",
    color: "#D97706",
    yMin: 3.5,
    yMax: 7,
    xMin: 5,
    xMax: 10,
    ...metersToGrid(5, 10, 3.5, 7),
    description: "Mid-court advantage side",
    tacticalAdvice: "Avoid lingering in no-man's land",
    isPressureZone: true,
  },
  // Defense zones (0-3.5m from back wall)
  {
    id: "defense-deuce",
    name: "Defense Deuce",
    emoji: "🛡️",
    color: "#EF4444",
    yMin: 0,
    yMax: 3.5,
    xMin: 0,
    xMax: 5,
    ...metersToGrid(0, 5, 0, 3.5),
    description: "Back court deuce corner",
    tacticalAdvice: "Use glass walls, lob to reset",
    isPressureZone: true,
  },
  {
    id: "defense-ad",
    name: "Defense Ad",
    emoji: "🛡️",
    color: "#DC2626",
    yMin: 0,
    yMax: 3.5,
    xMin: 5,
    xMax: 10,
    ...metersToGrid(5, 10, 0, 3.5),
    description: "Back court advantage corner",
    tacticalAdvice: "Recover position, look for counter",
    isPressureZone: true,
  },
];

// 9-Zone Grid System - Detailed 3×3 analysis (HALF COURT)
const NINE_ZONE_SYSTEM: ZoneDefinition[] = [
  // Row 1: Net (6.67-10m from back wall)
  {
    id: "net-left",
    name: "Net Left",
    emoji: "1️⃣",
    color: "#10B981",
    yMin: 6.67,
    yMax: 10,
    xMin: 0,
    xMax: 3.33,
    ...metersToGrid(0, 3.33, 6.67, 10),
    description: "Net left corner",
    tacticalAdvice: "Strong position for right-handed players",
  },
  {
    id: "net-center",
    name: "Net Center",
    emoji: "2️⃣",
    color: "#059669",
    yMin: 6.67,
    yMax: 10,
    xMin: 3.33,
    xMax: 6.67,
    ...metersToGrid(3.33, 6.67, 6.67, 10),
    description: "Net center - the T",
    tacticalAdvice: "Control the T, dominate the net",
  },
  {
    id: "net-right",
    name: "Net Right",
    emoji: "3️⃣",
    color: "#047857",
    yMin: 6.67,
    yMax: 10,
    xMin: 6.67,
    xMax: 10,
    ...metersToGrid(6.67, 10, 6.67, 10),
    description: "Net right corner",
    tacticalAdvice: "Strong position for left-handed players",
  },
  // Row 2: Mid (3.33-6.67m from back wall)
  {
    id: "mid-left",
    name: "Mid Left",
    emoji: "4️⃣",
    color: "#F59E0B",
    yMin: 3.33,
    yMax: 6.67,
    xMin: 0,
    xMax: 3.33,
    ...metersToGrid(0, 3.33, 3.33, 6.67),
    description: "Mid left",
    tacticalAdvice: "Transition point - move forward or back",
    isPressureZone: true,
  },
  {
    id: "mid-center",
    name: "Mid Center",
    emoji: "5️⃣",
    color: "#D97706",
    yMin: 3.33,
    yMax: 6.67,
    xMin: 3.33,
    xMax: 6.67,
    ...metersToGrid(3.33, 6.67, 3.33, 6.67),
    description: "Mid center - no-man's land",
    tacticalAdvice: "Danger zone! Avoid staying here",
    isPressureZone: true,
  },
  {
    id: "mid-right",
    name: "Mid Right",
    emoji: "6️⃣",
    color: "#B45309",
    yMin: 3.33,
    yMax: 6.67,
    xMin: 6.67,
    xMax: 10,
    ...metersToGrid(6.67, 10, 3.33, 6.67),
    description: "Mid right",
    tacticalAdvice: "Transition point - move forward or back",
    isPressureZone: true,
  },
  // Row 3: Back (0-3.33m from back wall)
  {
    id: "back-left",
    name: "Back Left",
    emoji: "7️⃣",
    color: "#EF4444",
    yMin: 0,
    yMax: 3.33,
    xMin: 0,
    xMax: 3.33,
    ...metersToGrid(0, 3.33, 0, 3.33),
    description: "Back left corner",
    tacticalAdvice: "Use corner glass walls creatively",
    isPressureZone: true,
  },
  {
    id: "back-center",
    name: "Back Center",
    emoji: "8️⃣",
    color: "#DC2626",
    yMin: 0,
    yMax: 3.33,
    xMin: 3.33,
    xMax: 6.67,
    ...metersToGrid(3.33, 6.67, 0, 3.33),
    description: "Back center",
    tacticalAdvice: "Standard defensive position",
    isPressureZone: true,
  },
  {
    id: "back-right",
    name: "Back Right",
    emoji: "9️⃣",
    color: "#B91C1C",
    yMin: 0,
    yMax: 3.33,
    xMin: 6.67,
    xMax: 10,
    ...metersToGrid(6.67, 10, 0, 3.33),
    description: "Back right corner",
    tacticalAdvice: "Use corner glass walls creatively",
    isPressureZone: true,
  },
];

// Functional Zone System (Advanced) - Based on shot types (HALF COURT)
const FUNCTIONAL_ZONES: ZoneDefinition[] = [
  {
    id: "volley",
    name: "Volley Zone",
    emoji: "🎯",
    color: "#10B981",
    yMin: 8.5,
    yMax: 10,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 8.5, 10),
    description: "Prime finishing area",
    tacticalAdvice: "Take the ball early, put away with power",
  },
  {
    id: "bandeja",
    name: "Bandeja Zone",
    emoji: "🏸",
    color: "#3B82F6",
    yMin: 6,
    yMax: 8.5,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 6, 8.5),
    description: "Bandeja and vibora territory",
    tacticalAdvice: "Control shots, push opponents back",
  },
  {
    id: "no-mans-land",
    name: "No-Man's Land",
    emoji: "⚠️",
    color: "#F59E0B",
    yMin: 4,
    yMax: 6,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 4, 6),
    description: "Danger zone - transition only",
    tacticalAdvice: "Never stay here! Move forward or back",
    isPressureZone: true,
  },
  {
    id: "service-box",
    name: "Service Box",
    emoji: "📦",
    color: "#8B5CF6",
    yMin: 2,
    yMax: 4,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 2, 4),
    description: "Rally building area",
    tacticalAdvice: "Work the point, look for net approach",
    isPressureZone: true,
  },
  {
    id: "glass-wall",
    name: "Glass Wall Zone",
    emoji: "🧱",
    color: "#EF4444",
    yMin: 0,
    yMax: 2,
    xMin: 0,
    xMax: 10,
    ...metersToGrid(0, 10, 0, 2),
    description: "Defensive survival area",
    tacticalAdvice: "Use walls creatively, lob to reset",
    isPressureZone: true,
  },
];

// All zone systems
export const ZONE_SYSTEMS: ZoneSystem[] = [
  {
    id: "traffic-light",
    name: "Traffic Light",
    description: "Simple 3-zone system (Green/Orange/Red)",
    zones: TRAFFIC_LIGHT_ZONES,
    coachingTips:
      "Coaches use the Traffic Light system to teach court positioning basics. Green zone (net) is where you want to be to finish points. Orange zone (transition) should be crossed quickly—don't linger here. Red zone (defense) means you're under pressure; use lobs to reset and work your way forward.",
  },
  {
    id: "6-zone",
    name: "6-Zone Tactical",
    description: "Split by depth and court side",
    zones: SIX_ZONE_SYSTEM,
    coachingTips:
      "The 6-Zone system helps coaches analyze court side balance. Players should control their side while being ready to cover the middle. Watch for patterns: Are you spending too much time on one side? Good teams rotate smoothly between deuce and ad sides while maintaining net presence.",
  },
  {
    id: "9-zone",
    name: "9-Zone Grid",
    description: "Detailed 3×3 grid analysis",
    zones: NINE_ZONE_SYSTEM,
    coachingTips:
      "The 9-Zone grid provides granular positioning data. Coaches use this to identify specific weaknesses—like a player stuck in back corners or avoiding the center. Elite players dominate the net-center (the 'T') and minimize time in mid-court zones. Compare your heat map to pros to spot improvement areas.",
  },
  {
    id: "functional",
    name: "Functional",
    description: "Based on shot types and tactics",
    zones: FUNCTIONAL_ZONES,
    coachingTips:
      "The Functional system maps zones to shot types. Volley zone is for finishing with power. Bandeja zone is where you control with overhead shots. No-man's land is dangerous—never stay here! Service box is for building points. Glass wall zone means you're defending; use the walls creatively to reset.",
  },
];



