import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { RadixThemeProvider } from "@/components/RadixThemeProvider";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { LibraryTasksProvider } from "@/components/sidebar/LibraryTasksContext";
import { CookieConsent } from "@/components/consent";
import { AnalyticsProvider } from "@/lib/analytics";
// Import Radix CSS in proper order to allow overrides
import "@radix-ui/themes/tokens.css";
import "@radix-ui/themes/components.css";
import "./globals.css"; // Our custom styles go here, between components and utilities
import "@radix-ui/themes/utilities.css";

// Optimize font loading with next/font
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap", // Use font-display: swap for better performance
  preload: true,
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    default: "SportAI Open",
    template: "%s | SportAI"
  },
  description: "Advanced AI-powered sports video analysis for tennis, pickleball, and padel. Get expert coaching insights, technique analysis, and performance recommendations.",
  keywords: ["sports analysis", "AI coach", "video analysis", "tennis", "pickleball", "padel", "sports coaching", "technique analysis"],
  authors: [{ name: "SportAI" }],
  creator: "SportAI",
  publisher: "SportAI",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: "SportAI - AI-Powered Sports Video Analysis",
    description: "Get expert AI coaching insights for tennis, pickleball, and padel. Analyze your technique and improve your game.",
    type: "website",
    locale: "en_US",
    siteName: "SportAI",
    // images are auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "SportAI - AI-Powered Sports Video Analysis",
    description: "Get expert AI coaching insights for tennis, pickleball, and padel.",
    // images are auto-generated by app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'SportAI',
  },
};

// Separate viewport export (Next.js 15 requirement)
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#1C1C1C' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && process.env.NODE_ENV === 'production' && (
        <>
          {/* Google Consent Mode v2 - must be set BEFORE gtag loads */}
          <Script id="google-consent-mode" strategy="beforeInteractive">
            {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});`}
          </Script>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`gtag('js',new Date());gtag('config','${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}')`}
          </Script>
        </>
      )}
      <body className="font-sans" suppressHydrationWarning>
        <RadixThemeProvider>
          <AuthProvider>
            <LibraryTasksProvider>
              <AnalyticsProvider>
                {children}
              </AnalyticsProvider>
              <CookieConsent />
            </LibraryTasksProvider>
{process.env.NODE_ENV === 'production' && (
              <>
                <SpeedInsights />
                <Analytics />
              </>
            )}
          </AuthProvider>
        </RadixThemeProvider>
      </body>
    </html>
  );
}

